# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4571fa07db61bd35fa33d765cf20d812d4bcfb8d7ce0ef1fa0b581d52aa5d8cf1c1a273fb0f21f1279df989f5b5da7bfb5c5509cea8d4e8fa5b6bc6f499dbe60

test:
  secret_key_base: 578690c6ed2dfb8e6cc5ccd5f17f51d1514f517f1cf82c983323c17d8a4a37e0cadc310bba4e55ba26bcbb3e1bda47ad8769ce99787c19452ad1bb3043af0073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
